#!/bin/bash

# CoPipes Codespace setup script
# Generates .env files from GitHub Codespace secrets and starts all services.
#
# Usage (run once per new Codespace):
#   bash .devcontainer/setup.sh
#
# For subsequent restarts of the same Codespace:
#   ./start.sh up

set -e

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── Guard: must run inside a GitHub Codespace ─────────────────────────────
if [ -z "$CODESPACE_NAME" ]; then
    echo "[-] This script is intended for GitHub Codespaces."
    echo "    For local development, create .env and supabase/.env manually."
    exit 1
fi

echo "[*] Setting up CoPipes in Codespace: $CODESPACE_NAME"
echo ""

chmod +x "$ROOT_DIR/start.sh"

# ── Validate required Codespace secrets ───────────────────────────────────
REQUIRED_SECRETS=(
    POSTGRES_PASSWORD
    JWT_SECRET
    ANON_KEY
    SERVICE_ROLE_KEY
    DASHBOARD_PASSWORD
    SECRET_KEY_BASE
    VAULT_ENC_KEY
    PG_META_CRYPTO_KEY
    AIRFLOW_ADMIN_PASSWORD
    AIRFLOW_WEBSERVER_SECRET_KEY
    LOGFLARE_PUBLIC_ACCESS_TOKEN
    LOGFLARE_PRIVATE_ACCESS_TOKEN
)

missing=()
for var in "${REQUIRED_SECRETS[@]}"; do
    [ -z "${!var}" ] && missing+=("$var")
done

if [ ${#missing[@]} -gt 0 ]; then
    echo "[-] Missing required Codespace secrets:"
    for var in "${missing[@]}"; do
        echo "    - $var"
    done
    echo ""
    echo "    Define them at: GitHub repo → Settings → Secrets and variables → Codespaces"
    echo "    Then recreate the Codespace for secrets to take effect."
    exit 1
fi

# ── Compute public Codespace URLs ─────────────────────────────────────────
DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
SUPABASE_URL="https://${CODESPACE_NAME}-8001.${DOMAIN}"
API_URL="https://${CODESPACE_NAME}-8000.${DOMAIN}"
FRONTEND_URL="https://${CODESPACE_NAME}-3000.${DOMAIN}"

echo "[*] Service URLs:"
echo "    Frontend:  $FRONTEND_URL"
echo "    FastAPI:   $API_URL"
echo "    Supabase:  $SUPABASE_URL"
echo ""

# ── Generate root .env ────────────────────────────────────────────────────
cat > "$ROOT_DIR/.env" <<EOF
# Generated by .devcontainer/setup.sh — do not edit manually

# Airflow database
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@supabase-db:5432/airflow
AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
AIRFLOW_API_URL=http://airflow-webserver:8080/api/v1

# Airflow admin
AIRFLOW_ADMIN_USERNAME=admin
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AIRFLOW_ADMIN_EMAIL=admin@example.com

# Service URLs
NEXT_PUBLIC_API_URL=${API_URL}
FRONTEND_URL=${FRONTEND_URL}

# Supabase — internal Docker URL (used by FastAPI)
SUPABASE_PUBLIC_URL=http://supabase-kong:8000
SUPABASE_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Supabase — public Codespace URL (used by browser)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}

JWT_SECRET=${JWT_SECRET}
EOF

# ── Generate supabase/.env ────────────────────────────────────────────────
cat > "$ROOT_DIR/supabase/.env" <<EOF
# Generated by .devcontainer/setup.sh — do not edit manually

# Secrets
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}

# Database
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

# Connection pooler
POOLER_PROXY_PORT_TRANSACTION=6543
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_TENANT_ID=your-tenant-id
POOLER_DB_POOL_SIZE=5

# Kong
KONG_HTTP_PORT=8001
KONG_HTTPS_PORT=8444

# PostgREST
PGRST_DB_SCHEMAS=public,storage,graphql_public

# Auth
SITE_URL=${FRONTEND_URL}
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
API_EXTERNAL_URL=${SUPABASE_URL}
MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true

# Studio
STUDIO_DEFAULT_ORGANIZATION=Default Organization
STUDIO_DEFAULT_PROJECT=Default Project
SUPABASE_PUBLIC_URL=${SUPABASE_URL}
IMGPROXY_ENABLE_WEBP_DETECTION=true
OPENAI_API_KEY=

# Edge functions
FUNCTIONS_VERIFY_JWT=false

# Analytics
LOGFLARE_PUBLIC_ACCESS_TOKEN=${LOGFLARE_PUBLIC_ACCESS_TOKEN}
LOGFLARE_PRIVATE_ACCESS_TOKEN=${LOGFLARE_PRIVATE_ACCESS_TOKEN}

# Docker
DOCKER_SOCKET_LOCATION=/var/run/docker.sock
GOOGLE_PROJECT_ID=GOOGLE_PROJECT_ID
GOOGLE_PROJECT_NUMBER=GOOGLE_PROJECT_NUMBER
EOF

echo "[+] Environment files generated."
echo ""
echo "[*] Starting services (first run pulls Docker images — this may take a few minutes)..."
echo ""
"$ROOT_DIR/start.sh" up
